name: firebase-auto-deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: deploy
      run: |
        sudo npm i -g firebase-tools
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}